<a href="https://colab.research.google.com/github/arunkumarbhagat/IPL-Prediction-Model/blob/main/ilp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
match= pd.read_csv('/content/matches[2].csv')
delivery= pd.read_csv('/content/deliveries[1].csv')

In [ ]:
match.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [ ]:
match.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [ ]:
delivery.isnull().sum()

match_id                0
inning                  0
batting_team            0
bowling_team            0
over                    0
ball                    0
batter                  0
bowler                  0
non_striker             1
batsman_runs            1
extra_runs              1
total_runs              1
extras_type         86946
is_wicket               1
player_dismissed    87490
dismissal_kind      87490
fielder             88771
dtype: int64

In [ ]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0.0,1.0,1.0,legbyes,0.0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN

In [ ]:
delivery.groupby(['match_id','inning']).sum()['total_runs']

match_id  inning
335982    1         222.0
          2          82.0
335983    1         240.0
          2         207.0
335984    1         129.0
                    ...
598061    1         170.0
          2         163.0
598062    1         168.0
          2         135.0
598063    1          35.0
Name: total_runs, Length: 782, dtype: float64

In [ ]:
total_score_df=delivery.groupby(['match_id','inning']).sum()['total_runs']+1

In [ ]:
total_score_df

match_id  inning
335982    1         223.0
          2          83.0
335983    1         241.0
          2         208.0
335984    1         130.0
                    ...
598061    1         171.0
          2         164.0
598062    1         169.0
          2         136.0
598063    1          36.0
Name: total_runs, Length: 782, dtype: float64

In [ ]:
match.shape

(1095, 20)

In [ ]:
delivery.shape

(92042, 17)

In [ ]:
total_score_df =total_score_df[total_score_df.index.get_level_values('inning')==1]

In [ ]:
total_score_df

match_id  inning
335982    1         223.0
335983    1         241.0
335984    1         130.0
335985    1         166.0
335986    1         111.0
                    ...
598059    1         121.0
598060    1         179.0
598061    1         171.0
598062    1         169.0
598063    1          36.0
Name: total_runs, Length: 388, dtype: float64

In [ ]:
match.merge(total_score_df.reset_index()[['match_id','total_runs']],left_on='id',right_on='match_id')

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,total_runs
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,335982,223.0
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,335983,241.0
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,335984,130.0
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,335985,166.0
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,335986,111.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,598045,2013,Bangalore,2013-05-14,League,AC Gilchrist,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,...,wickets,7.0,175.0,20.0,N,NaN,HDPK Dharmasena,S Ravi,598045,175.0
384,598062,2013,Chennai,2013-05-14,League,MS Dhoni,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,...,runs,33.0,169.0,20.0,N,NaN,C Shamshuddin,RJ Tucker,598062,169.0
385,598061,2013,Ranchi,2013-05-15,League,MK Pandey,JSCA International Stadium Complex,Kolkata Knight Riders,Pune Warriors,Kolkata Knight Riders,...,runs,7.0,171.0,20.0,N,NaN,NJ Llong,K Srinath,598061,171.0
386,598063,2013,Mumbai,2013-05-15,League,AP Tare,Wankhede Stadium,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,...,runs,14.0,167.0,20.0,N,NaN,Asad Rauf,S Asnani,598063,36.0
387,598028,2013,Dharamsala,2013-05-16,League,DA Miller,Himachal Pradesh Cricket Association Stadium,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,...,runs,7.0,172.0,20.0,N,NaN,HDPK Dharmasena,S Ravi,598028,172.0

In [ ]:
match_df=match.merge(total_score_df.reset_index()[['match_id','total_runs']],left_on='id',right_on='match_id')

In [ ]:
match_df.isnull().sum()

id                   0
season               0
city                 0
date                 0
match_type           0
player_of_match      1
venue                0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               1
result               0
result_margin        5
target_runs          1
target_overs         1
super_over           0
method             380
umpire1              0
umpire2              0
match_id             0
total_runs           0
dtype: int64

In [ ]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad'],
      dtype=object)

In [ ]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals',
    'Gujarat Titans',
    'Lucknow Super Giants',

]

In [ ]:
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils', 'Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

In [ ]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [ ]:
match_df.shape

(330, 22)

In [ ]:
match_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 330 entries, 0 to 387
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               330 non-null    int64
 1   season           330 non-null    object
 2   city             330 non-null    object
 3   date             330 non-null    object
 4   match_type       330 non-null    object
 5   player_of_match  330 non-null    object
 6   venue            330 non-null    object
 7   team1            330 non-null    object
 8   team2            330 non-null    object
 9   toss_winner      330 non-null    object
 10  toss_decision    330 non-null    object
 11  winner           330 non-null    object
 12  result           330 non-null    object
 13  result_margin    326 non-null    float64
 14  target_runs      330 non-null    float64
 15  target_overs     330 non-null    float64
 16  super_over       330 non-null    object
 17  method           7 non-null      object
 18  umpire1          330 non-null    object
 19  umpire2          330 non-null    object
 20  match_id         330 non-null    int64
 21  total_runs       330 non-null    float64
dtypes: float64(4), int64(2), object(16)
memory usage: 59.3+ KB

In [ ]:
match_df=match_df[['match_id','city','winner','total_runs']]

In [ ]:
delivery_df=match_df.merge(delivery,on='match_id')

In [ ]:
delivery_df.isnull().sum()

match_id                0
city                    0
winner                  0
total_runs_x            0
inning                  0
batting_team            0
bowling_team            0
over                    0
ball                    0
batter                  0
bowler                  0
non_striker             1
batsman_runs            1
extra_runs              1
total_runs_y            1
extras_type         74013
is_wicket               1
player_dismissed    74558
dismissal_kind      74558
fielder             75639
dtype: int64

In [ ]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0.0,1.0,1.0,legbyes,0.0,NaN,NaN,NaN
1,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
2,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN
3,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
4,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78437,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,2,M Morkel,PP Chawla,CM Gautam,6.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN
78438,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,3,M Morkel,PP Chawla,CM Gautam,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN
78439,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,4,CM Gautam,PP Chawla,M Morkel,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN
78440,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,5,M Morkel,PP Chawla,CM Gautam,6.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN
78441,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,6,M Morkel,PP Chawla,CM Gautam,0.0,0.0,0.0,NaN,1.0,M Morkel,caught,DA Miller

In [ ]:
delivery_df=delivery_df[delivery_df['inning']==2]

In [ ]:
delivery_df.shape

(37865, 20)

In [ ]:
delivery_df['current_score']=delivery_df.groupby(['match_id'])['total_runs_y'].cumsum()

<ipython-input-32-61ebf5f5189f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['current_score']=delivery_df.groupby(['match_id'])['total_runs_y'].cumsum()

In [ ]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37865 entries, 124 to 78441
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          37865 non-null  int64
 1   city              37865 non-null  object
 2   winner            37865 non-null  object
 3   total_runs_x      37865 non-null  float64
 4   inning            37865 non-null  int64
 5   batting_team      37865 non-null  object
 6   bowling_team      37865 non-null  object
 7   over              37865 non-null  int64
 8   ball              37865 non-null  int64
 9   batter            37865 non-null  object
 10  bowler            37865 non-null  object
 11  non_striker       37865 non-null  object
 12  batsman_runs      37865 non-null  float64
 13  extra_runs        37865 non-null  float64
 14  total_runs_y      37865 non-null  float64
 15  extras_type       2149 non-null   object
 16  is_wicket         37865 non-null  float64
 17  player_dismissed  1850 non-null   object
 18  dismissal_kind    1850 non-null   object
 19  fielder           1323 non-null   object
 20  current_score     37865 non-null  float64
dtypes: float64(6), int64(4), object(11)
memory usage: 6.4+ MB

In [ ]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,1.0
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,R Dravid,0.0,1.0,1.0,wides,0.0,NaN,NaN,NaN,2.0
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,R Dravid,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,2.0
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,R Dravid,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,3.0
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,W Jaffer,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78437,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,2,M Morkel,...,CM Gautam,6.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN,156.0
78438,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,3,M Morkel,...,CM Gautam,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,157.0
78439,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,4,CM Gautam,...,M Morkel,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,158.0
78440,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,5,M Morkel,...,CM Gautam,6.0,0.0,6.0,NaN,0.0,NaN,NaN,NaN,164.0
78441,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,6,M Morkel,...,CM Gautam,0.0,0.0,0.0,NaN,1.0,M Morkel,caught,DA Miller,164.0

In [ ]:
delivery_df['runs_left']=delivery_df['total_runs_x']-delivery_df['current_score']

<ipython-input-35-da891a150688>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['runs_left']=delivery_df['total_runs_x']-delivery_df['current_score']

In [ ]:
delivery_df['balls_left'] = 126 - ((delivery_df['over']+1) * 6 + (delivery_df['ball']))

<ipython-input-36-84eb9277e736>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['balls_left'] = 126 - ((delivery_df['over']+1) * 6 + (delivery_df['ball']))

In [ ]:
delivery_df['player_dismissed'].unique()

array([nan, 'R Dravid', 'V Kohli', 'JH Kallis', 'W Jaffer', 'MV Boucher',
       'B Akhil', 'CL White', 'AA Noffke', 'Z Khan', 'SB Joshi', 'K Goel',
       'JR Hopes', 'Yuvraj Singh', 'KC Sangakkara', 'V Sehwag',
       'S Chanderpaul', 'LRPL Taylor', 'BB McCullum', 'RT Ponting',
       'WP Saha', 'SC Ganguly', 'Mohammad Hafeez', 'M Kaif', 'YK Pathan',
       'Kamran Akmal', 'DS Lehmann', 'G Gambhir', 'L Ronchi',
       'ST Jayasuriya', 'RV Uthappa', 'SM Pollock', 'DJ Bravo',
       'MA Khote', 'Harbhajan Singh', 'SR Watson', 'GC Smith',
       'RA Jadeja', 'D Salunkhe', 'SS Tiwary', 'AM Nayar', 'M Rawat',
       'PA Patel', 'DPMD Jayawardene', 'SM Katich', 'TM Srivastava',
       'IK Pathan', 'B Chipli', 'P Kumar', 'DW Steyn', 'AM Rahane',
       'MK Pandey', 'RR Sarwan', 'Salman Butt', 'AB Agarkar', 'BJ Hodge',
       'LR Shukla', 'DJ Hussey', 'DB Das', 'Umar Gul', 'AB Dinda',
       'AC Gilchrist', 'HH Gibbs', 'RG Sharma', 'Shahid Afridi',
       'VVS Laxman', 'SB Styris', 'S Dhawan', 'AB de Villiers',
       'Shoaib Malik', 'KD Karthik', 'PJ Sangwan', 'R Bhatia',
       'Mohammad Asif', 'GD McGrath', 'SA Asnodkar', 'SE Marsh',
       'YV Takawale', 'S Vidyut', 'SP Fleming', 'SK Raina', 'JA Morkel',
       'MS Dhoni', 'CK Kapugedera', 'J Arunkumar', 'PP Chawla',
       'VRV Singh', 'DB Ravi Teja', 'SB Bangar', 'WPUJC Vaas',
       'AD Mascarenhas', 'SK Warne', 'MK Tiwary', 'TM Dilshan',
       'MF Maharoof', 'A Mishra', 'VY Mahesh', 'SR Tendulkar',
       'Y Venugopal Rao', 'PP Ojha', 'RP Singh', 'Misbah-ul-Haq',
       'DT Patil', 'A Kumble', 'LPC Silva', 'H Das', 'Sohail Tanvir',
       'DR Smith', 'PR Shah', 'SD Chitnis', 'A Nehra', 'VS Yeligati',
       'S Badrinath', 'MS Gony', 'L Balaji', 'LA Pomersbach', 'A Mukund',
       'A Chopra', 'Younis Khan', 'NK Patel', 'A Flintoff', 'ML Hayden',
       'JDP Oram', 'T Henderson', 'MM Patel', 'Kamran Khan',
       'KP Pietersen', 'R Bishnoi', 'R Vinay Kumar', 'JD Ryder',
       'KV Sharma', 'Joginder Sharma', 'CH Gayle', 'Yashpal Singh',
       'I Sharma', 'RS Bopara', 'JP Duminy', 'RJ Quiney', 'AS Raut',
       'AN Ghosh', 'BAW Mendis', 'PC Valthaty', 'SP Goswami',
       'RE van der Merwe', 'SK Trivedi', 'MN van Wyk', 'NV Ojha',
       'LA Carseldine', 'DA Warner', 'M Manhas', 'S Sohal', 'RJ Harris',
       'TL Suman', 'WA Mota', 'M Vijay', 'M Morkel', 'A Symonds',
       'Shoaib Ahmed', 'DS Kulkarni', 'C Nanda', 'SL Malinga', 'J Botha',
       'A Singh', 'SS Shaikh', 'B Lee', 'AA Bilakhia', 'Anirudh Singh',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'JM Kemp', 'R Ashwin',
       'M Muralitharan', 'OA Shah', 'AD Mathews', 'RS Gavaskar',
       'SE Bond', 'M Kartik', 'DP Nannes', 'MS Bisla', 'AB Barath',
       'CA Pujara', 'MC Henriques', 'Y Nagar', 'S Ladda', 'KA Pollard',
       'GJ Bailey', 'J Theron', 'SJ Srivastava', 'R Sathish',
       'EJG Morgan', 'MJ Lumb', 'MD Mishra', 'Jaskaran Singh',
       'KAJ Roach', 'Mandeep Singh', 'CK Langeveldt', 'AT Rayudu',
       'FY Fazal', 'AC Voges', 'S Narwal', 'SW Tait', 'R Sharma',
       'A Mithun', 'Harmeet Singh', 'R McLaren', 'PD Collingwood',
       'KM Jadhav', 'S Sriram', 'AP Dole', 'KP Appanna', 'MR Marsh',
       'Pankaj Singh', 'B Sumanth', 'AG Paunikar', 'DJ Jacobs',
       'IR Jaggi', 'DT Christian', 'AL Menaria', 'Sunny Singh',
       'MA Agarwal', 'JJ van der Wath', 'R Ninan', 'AUK Pathan',
       'AJ Finch', 'STR Binny', 'MEK Hussey', 'S Anirudha', 'S Randiv',
       'TR Birt', 'Bipul Sharma', 'CA Ingram', 'S Nadeem', 'DH Yagnik',
       'AC Blizzard', 'AB McDonald', 'KB Arun Karthik', 'BA Bhatt',
       'JEC Franklin', 'DL Vettori', 'RE Levi', 'GJ Maxwell', 'DJ Harris',
       'Ankit Sharma', 'SP Narine', 'HV Patel', 'KK Cooper', 'AA Chavan',
       'GB Hogg', 'F du Plessis', 'Shakib Al Hasan', 'RN ten Doeschate',
       'N Saini', 'Azhar Mahmood', 'RJ Peterson', 'A Ashish Reddy',
       'Gurkeerat Singh', 'PA Reddy', 'UBT Chand', 'AD Russell',
       'UT Yadav', 'CA Lynn', 'P Negi', 'Sunny Gupta', 'VR Aaron',
       'MC Juneja', 'B Laughlin', 'NLTC Perera', 'Mohammed Shami',
       'BMAJ Mendis', 'GH Vihari', 'SMSM Senanayake', 'KL Rahul',
       'J Syed Mohammad', 'R Dhawan', 'MG Johnson', 'Q de Kock',
       'BB Samantray', 'M Vohra', 'SV Samson', 'DA Miller', 'CH Morris',
       'MM Sharma', 'DJG Sammy', 'BJ Rohrer', 'P Awana', 'JP Faulkner'],
      dtype=object)

In [ ]:
valid_names=['R Dravid', 'V Kohli', 'JH Kallis', 'W Jaffer', 'MV Boucher',
       'B Akhil', 'CL White', 'AA Noffke', 'Z Khan', 'SB Joshi', 'K Goel',
       'JR Hopes', 'Yuvraj Singh', 'KC Sangakkara', 'V Sehwag',
       'S Chanderpaul', 'LRPL Taylor', 'BB McCullum', 'RT Ponting',
       'WP Saha', 'SC Ganguly', 'Mohammad Hafeez', 'M Kaif', 'YK Pathan',
       'Kamran Akmal', 'DS Lehmann', 'G Gambhir', 'L Ronchi',
       'ST Jayasuriya', 'RV Uthappa', 'SM Pollock', 'DJ Bravo',
       'MA Khote', 'Harbhajan Singh', 'SR Watson', 'GC Smith',
       'RA Jadeja', 'D Salunkhe', 'SS Tiwary', 'AM Nayar', 'M Rawat',
       'PA Patel', 'DPMD Jayawardene', 'SM Katich', 'TM Srivastava',
       'IK Pathan', 'B Chipli', 'P Kumar', 'DW Steyn', 'AM Rahane',
       'MK Pandey', 'RR Sarwan', 'Salman Butt', 'AB Agarkar', 'BJ Hodge',
       'LR Shukla', 'DJ Hussey', 'DB Das', 'Umar Gul', 'AB Dinda',
       'AC Gilchrist', 'HH Gibbs', 'RG Sharma', 'Shahid Afridi',
       'VVS Laxman', 'SB Styris', 'S Dhawan', 'AB de Villiers',
       'Shoaib Malik', 'KD Karthik', 'PJ Sangwan', 'R Bhatia',
       'Mohammad Asif', 'GD McGrath', 'SA Asnodkar', 'SE Marsh',
       'YV Takawale', 'S Vidyut', 'SP Fleming', 'SK Raina', 'JA Morkel',
       'MS Dhoni', 'CK Kapugedera', 'J Arunkumar', 'PP Chawla',
       'VRV Singh', 'DB Ravi Teja', 'SB Bangar', 'WPUJC Vaas',
       'AD Mascarenhas', 'SK Warne', 'MK Tiwary', 'TM Dilshan',
       'MF Maharoof', 'A Mishra', 'VY Mahesh', 'SR Tendulkar',
       'Y Venugopal Rao', 'PP Ojha', 'RP Singh', 'Misbah-ul-Haq',
       'DT Patil', 'A Kumble', 'LPC Silva', 'H Das', 'Sohail Tanvir',
       'DR Smith', 'PR Shah', 'SD Chitnis', 'A Nehra', 'VS Yeligati',
       'S Badrinath', 'MS Gony', 'L Balaji', 'LA Pomersbach', 'A Mukund',
       'A Chopra', 'Younis Khan', 'NK Patel', 'A Flintoff', 'ML Hayden',
       'JDP Oram', 'T Henderson', 'MM Patel', 'Kamran Khan',
       'KP Pietersen', 'R Bishnoi', 'R Vinay Kumar', 'JD Ryder',
       'KV Sharma', 'Joginder Sharma', 'CH Gayle', 'Yashpal Singh',
       'I Sharma', 'RS Bopara', 'JP Duminy', 'RJ Quiney', 'AS Raut',
       'AN Ghosh', 'BAW Mendis', 'PC Valthaty', 'SP Goswami',
       'RE van der Merwe', 'SK Trivedi', 'MN van Wyk', 'NV Ojha',
       'LA Carseldine', 'DA Warner', 'M Manhas', 'S Sohal', 'RJ Harris',
       'TL Suman', 'WA Mota', 'M Vijay', 'M Morkel', 'A Symonds',
       'Shoaib Ahmed', 'DS Kulkarni', 'C Nanda', 'SL Malinga', 'J Botha',
       'A Singh', 'SS Shaikh', 'B Lee', 'AA Bilakhia', 'Anirudh Singh',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'JM Kemp', 'R Ashwin',
       'M Muralitharan', 'OA Shah', 'AD Mathews', 'RS Gavaskar',
       'SE Bond', 'M Kartik', 'DP Nannes', 'MS Bisla', 'AB Barath',
       'CA Pujara', 'MC Henriques', 'Y Nagar', 'S Ladda', 'KA Pollard',
       'GJ Bailey', 'J Theron', 'SJ Srivastava', 'R Sathish',
       'EJG Morgan', 'MJ Lumb', 'MD Mishra', 'Jaskaran Singh',
       'KAJ Roach', 'Mandeep Singh', 'CK Langeveldt', 'AT Rayudu',
       'FY Fazal', 'AC Voges', 'S Narwal', 'SW Tait', 'R Sharma',
       'A Mithun', 'Harmeet Singh', 'R McLaren', 'PD Collingwood',
       'KM Jadhav', 'S Sriram', 'AP Dole', 'KP Appanna', 'MR Marsh',
       'Pankaj Singh', 'B Sumanth', 'AG Paunikar', 'DJ Jacobs',
       'IR Jaggi', 'DT Christian', 'AL Menaria', 'Sunny Singh',
       'MA Agarwal', 'JJ van der Wath', 'R Ninan', 'AUK Pathan',
       'AJ Finch', 'STR Binny', 'MEK Hussey', 'S Anirudha', 'S Randiv',
       'TR Birt', 'Bipul Sharma', 'CA Ingram', 'S Nadeem', 'DH Yagnik',
       'AC Blizzard', 'AB McDonald', 'KB Arun Karthik', 'BA Bhatt',
       'JEC Franklin', 'DL Vettori', 'RE Levi', 'GJ Maxwell', 'DJ Harris',
       'Ankit Sharma', 'SP Narine', 'HV Patel', 'KK Cooper', 'AA Chavan',
       'GB Hogg', 'F du Plessis', 'Shakib Al Hasan', 'RN ten Doeschate',
       'N Saini', 'Azhar Mahmood', 'RJ Peterson', 'A Ashish Reddy',
       'Gurkeerat Singh', 'PA Reddy', 'UBT Chand', 'AD Russell',
       'UT Yadav', 'CA Lynn', 'P Negi', 'Sunny Gupta', 'VR Aaron',
       'MC Juneja', 'B Laughlin', 'NLTC Perera', 'Mohammed Shami',
       'BMAJ Mendis', 'GH Vihari', 'SMSM Senanayake', 'KL Rahul',
       'J Syed Mohammad', 'R Dhawan', 'MG Johnson', 'Q de Kock',
       'BB Samantray', 'M Vohra', 'SV Samson', 'DA Miller', 'CH Morris',
       'MM Sharma', 'DJG Sammy', 'BJ Rohrer', 'P Awana', 'JP Faulkner',
       'Sachin Baby', 'AP Tare', 'NM Coulter-Nile', 'CJ Anderson',
       'CM Gautam', 'NJ Maddinson', 'AR Patel', 'JDS Neesham', 'B Kumar',
       'SPD Smith', 'TG Southee', 'PV Tambe', 'KK Nair', 'SA Yadav',
       'BR Dunk', 'RR Rossouw', 'MA Starc', 'KW Richardson', 'S Rana',
       'LMP Simmons', 'Imran Tahir', 'R Shukla', 'R Tewatia', 'SS Iyer',
       'SA Abbott', 'DJ Hooda', 'KS Williamson', 'Iqbal Abdulla',
       'SN Khan', 'D Wiese', 'HH Pandya', 'MJ McClenaghan',
       'Anureet Singh', 'PJ Cummins', 'Karanveer Singh', 'Sandeep Sharma',
       'J Suchith', 'JC Buttler', 'KH Pandya', 'NS Naik', 'JO Holder',
       'Parvez Rasool', 'MP Stoinis', 'Swapnil Singh', 'SW Billings',
       'CR Brathwaite', 'JJ Bumrah', 'HM Amla', 'N Rana', 'RR Pant',
       'F Behardien', 'KJ Abbott', 'C Munro', 'CJ Jordan', 'TM Head',
       'S Aravind', 'TS Mills', 'YS Chahal', 'BCJ Cutting', 'KC Cariappa',
       'C de Grandhomme', 'CR Woakes', 'K Rabada', 'S Badree',
       'MJ Guptill', 'SP Jackson', 'A Choudhary', 'MN Samuels',
       'Kuldeep Yadav', 'DL Chahar', 'MA Wood', 'RK Singh', 'V Shankar',
       'Rashid Khan', 'S Kaul', 'Washington Sundar', 'JJ Roy', 'TA Boult',
       'H Klaasen', 'RA Tripathi', 'BA Stokes', 'K Gowtham', 'JD Unadkat',
       'RK Bhui', 'JC Archer', 'PP Shaw', 'LE Plunkett', 'E Lewis',
       'Ishan Kishan', 'M Markande', 'Mustafizur Rahman', 'AJ Tye',
       'BB Sran', 'AS Rajpoot', 'Shubman Gill', 'Shivam Mavi',
       'MK Lomror', 'DJM Short', 'DR Shorey', 'AD Hales', 'MM Ali',
       'AD Nath', 'TK Curran', 'P Chopra', 'Mohammed Siraj', 'SO Hetmyer',
       'JM Bairstow', 'S Dube', 'P Ray Barman', 'S Gopal', 'S Lamichhane',
       'Mohammad Nabi', 'SD Lad', 'LS Livingstone', 'Abhishek Sharma',
       'KK Ahmed', 'AJ Turner', 'KMA Paul', 'R Parag', 'SN Thakur',
       'SE Rutherford', 'N Pooran', 'GC Viljoen', 'MJ Santner',
       'P Simran Singh', 'Mujeeb Ur Rahman', 'SM Curran', 'PK Garg',
       'RD Gaikwad', 'D Padikkal', 'JR Philippe', 'Navdeep Saini',
       'Ravi Bishnoi', 'Abdul Samad', 'I Udana', 'YBK Jaiswal',
       'SS Cottrell', 'Arshdeep Singh', 'N Jagadeesan', 'T Banton',
       'KL Nagarkoti', 'AT Carey', 'TU Deshpande', 'A Nortje',
       'Kartik Tyagi', 'DR Sams', 'RM Patidar', 'Shahbaz Ahmed',
       'KA Jamieson', 'Virat Singh', 'CV Varun', 'M Prasidh Krishna',
       'Anmolpreet Singh', 'AF Milne', 'RD Chahar', 'VR Iyer',
       'KS Bharat', 'RV Patel', 'Anuj Rawat', 'GD Phillips', 'C Sakariya',
       'TL Seifert', 'R Powell', 'MS Wade', 'R Shepherd', 'DJ Willey',
       'PWH de Silva', 'Tilak Varma', 'TH David', 'M Ashwin',
       'Lalit Yadav', 'AK Markram', 'Rasikh Salam', 'A Badoni',
       'PVD Chameera', 'SS Prabhudessai', 'Akash Deep',
       'HE van der Dussen', 'D Brevis', 'FA Allen', 'A Manohar',
       'AS Joseph', 'D Pretorius', 'B Sai Sudharsan', 'Shashank Singh',
       'B Indrajith', 'DP Conway', 'AS Roy', 'Harshit Rana',
       'Umran Malik', 'Ramandeep Singh', 'K Kartikeya', 'KS Sharma',
       'Mohsin Khan', 'Avesh Khan', 'T Stubbs', 'HR Shokeen', 'M Jansen',
       'R Sanjay Yadav', 'A Tomar', 'Aman Hakim Khan', 'HC Brook',
       'AU Rashid', 'KR Mayers', 'MG Bracewell', 'Abishek Porel',
       'Rahmanullah Gurbaz', 'YV Dhull', 'N Wadhera', 'Dhruv Jurel',
       'WD Parnell', 'PD Salt', 'C Green', 'Arjun Tendulkar',
       'Naveen-ul-Haq', 'Noor Ahmad', 'JE Root', 'A Zampa', 'KM Asif',
       'Sanvir Singh', 'Vishnu Vinod', 'MD Shanaka', 'DG Nalkande',
       'PN Mankad', 'Naman Dhir', 'G Coetzee', 'Azmatullah Omarzai',
       'R Ravindra', 'DJ Mitchell', 'Sameer Rizvi', 'Sumit Kumar',
       'Kumar Kushagra', 'JA Richardson', 'BR Sharath', 'M Shahrukh Khan',
       'J Fraser-McGurk', 'A Raghuvanshi', 'SD Hope', 'R Sai Kishore',
       'Nithish Kumar Reddy', 'AA Kulkarni', 'Yudhvir Singh', 'SB Dubey',
       'D Ferreira', 'T Kohler-Cadmore']

In [ ]:
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:1 if x in valid_names else 0)

<ipython-input-39-54464a30b759>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:1 if x in valid_names else 0)

In [ ]:
delivery_df['player_dismissed'].head(25)

124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    1
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
Name: player_dismissed, dtype: int64

In [ ]:
delivery_df['wickets'] = 10 - delivery_df.groupby('match_id')['player_dismissed'].cumsum()

# Preview the result
delivery_df.head()

<ipython-input-41-e12a30b8329d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['wickets'] = 10 - delivery_df.groupby('match_id')['player_dismissed'].cumsum()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,1.0,NaN,0.0,0,NaN,NaN,1.0,222.0,119,10
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1.0,wides,0.0,0,NaN,NaN,2.0,221.0,118,10
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0.0,NaN,0.0,0,NaN,NaN,2.0,221.0,117,10
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,1.0,NaN,0.0,0,NaN,NaN,3.0,220.0,116,10
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,1.0,NaN,0.0,0,NaN,NaN,4.0,219.0,115,10

In [ ]:
delivery_df['crr']=(delivery_df["current_score"]*6)/(120-delivery_df["balls_left"])

<ipython-input-42-272d6e3c9d08>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['crr']=(delivery_df["current_score"]*6)/(120-delivery_df["balls_left"])

In [ ]:
match_df['city']=delivery_df['city']

In [ ]:
delivery_df['rrr']=(delivery_df['runs_left']*6)/delivery_df['balls_left']

<ipython-input-44-ee198925a9be>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['rrr']=(delivery_df['runs_left']*6)/delivery_df['balls_left']

In [ ]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets,crr,rrr
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0.0,0,NaN,NaN,1.0,222.0,119,10,6.000000,11.193277
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,0.0,0,NaN,NaN,2.0,221.0,118,10,6.000000,11.237288
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0.0,0,NaN,NaN,2.0,221.0,117,10,4.000000,11.333333
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0.0,0,NaN,NaN,3.0,220.0,116,10,4.500000,11.379310
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0.0,0,NaN,NaN,4.0,219.0,115,10,4.800000,11.426087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78437,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,2,M Morkel,...,0.0,0,NaN,NaN,156.0,16.0,4,4,8.068966,24.000000
78438,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,3,M Morkel,...,0.0,0,NaN,NaN,157.0,15.0,3,4,8.051282,30.000000
78439,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,4,CM Gautam,...,0.0,0,NaN,NaN,158.0,14.0,2,4,8.033898,42.000000
78440,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,5,M Morkel,...,0.0,0,NaN,NaN,164.0,8.0,1,4,8.268908,48.000000
78441,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,6,M Morkel,...,1.0,1,caught,DA Miller,164.0,8.0,0,3,8.200000,inf

In [ ]:
def firstInningWin(row):
    return 1 if row['batting_team']==row['winner'] else 0

In [ ]:
delivery_df['firstInningWin']=delivery_df.apply(firstInningWin,axis=1)

<ipython-input-47-7ed5850e94de>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['firstInningWin']=delivery_df.apply(firstInningWin,axis=1)

In [ ]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets,crr,rrr,firstInningWin
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,NaN,NaN,1.0,222.0,119,10,6.000000,11.193277,0
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,0,NaN,NaN,2.0,221.0,118,10,6.000000,11.237288,0
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,NaN,NaN,2.0,221.0,117,10,4.000000,11.333333,0
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0,NaN,NaN,3.0,220.0,116,10,4.500000,11.379310,0
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0,NaN,NaN,4.0,219.0,115,10,4.800000,11.426087,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78437,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,2,M Morkel,...,0,NaN,NaN,156.0,16.0,4,4,8.068966,24.000000,0
78438,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,3,M Morkel,...,0,NaN,NaN,157.0,15.0,3,4,8.051282,30.000000,0
78439,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,4,CM Gautam,...,0,NaN,NaN,158.0,14.0,2,4,8.033898,42.000000,0
78440,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,5,M Morkel,...,0,NaN,NaN,164.0,8.0,1,4,8.268908,48.000000,0
78441,598028,Dharamsala,Kings XI Punjab,172.0,2,Delhi Daredevils,Kings XI Punjab,19,6,M Morkel,...,1,caught,DA Miller,164.0,8.0,0,3,8.200000,inf,0

In [ ]:
final_df=delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_x','crr','rrr','firstInningWin']]

In [ ]:
final_df=final_df.sample(final_df.shape[0])

In [ ]:
final_df.dropna(inplace=True)

In [ ]:
final_df.isnull().sum()

batting_team      0
bowling_team      0
city              0
runs_left         0
balls_left        0
wickets           0
total_runs_x      0
crr               0
rrr               0
firstInningWin    0
dtype: int64

In [ ]:
final_df=final_df[final_df['balls_left']!=0]

In [ ]:
x=final_df.iloc[:,:-1]
y=final_df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train.isnull().sum()

batting_team    0
bowling_team    0
city            0
runs_left       0
balls_left      0
wickets         0
total_runs_x    0
crr             0
rrr             0
dtype: int64

In [ ]:
x_train.describe()

,runs_left,balls_left,wickets,total_runs_x,crr,rrr
count,30191.000000,30191.000000,30191.000000,30191.000000,30191.000000,30191.000000
mean,91.193005,63.255772,7.553907,160.957603,7.124596,10.275336
std,48.740271,33.163323,2.138853,28.865087,2.212160,14.220963
min,-15.000000,-2.000000,0.000000,68.000000,0.000000,-516.000000
25%,53.000000,35.000000,6.000000,142.000000,6.000000,6.954545
50%,90.000000,64.000000,8.000000,162.000000,7.166667,8.653846
75%,128.000000,92.000000,9.000000,180.000000,8.327586,10.764706
max,247.000000,119.000000,10.000000,247.000000,36.000000,552.000000

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Remove the 'sparse' argument and set 'handle_unknown' to 'ignore' for newer versions
trf = ColumnTransformer([
    ('trf', OneHotEncoder(drop='first', handle_unknown='ignore'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')

In [ ]:
#for probablity logistic Regression is best
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [ ]:
pipe= Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [ ]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [ ]:
y_pred=pipe.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8240593534711181

In [ ]:
pipe.predict_proba(x_test)[10]

array([0.5757706, 0.4242294])

In [ ]:
teams

['Sunrisers Hyderabad',
 'Mumbai Indians',
 'Royal Challengers Bangalore',
 'Kolkata Knight Riders',
 'Kings XI Punjab',
 'Chennai Super Kings',
 'Rajasthan Royals',
 'Delhi Capitals',
 'Gujarat Titans',
 'Lucknow Super Giants']

In [ ]:
delivery_df['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi'], dtype=object)

In [ ]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))